

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: population
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql    


  get_data:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: get_data_service
    command: poetry run python -m src.get_data
    working_dir: /src
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/population

    
  print_data:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: print_data_service
    command: poetry run python -m src.print_data
    working_dir: /src
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/population  
